# Список репозиториев, из которых мы будем брать хуки
repos:
  # Репозиторий с базовыми хуками
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0 # Используйте актуальную версию
    hooks:
      - id: check-yaml # Проверяет синтаксис YAML файлов
      - id: check-json # Проверяет синтаксис JSON файлов
      - id: end-of-file-fixer # Убеждается, что файл заканчивается пустой строкой
      - id: trailing-whitespace # Удаляет лишние пробелы в конце строк

  # Репозиторий с Ruff - нашим главным инструментом
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.4.9 # Используйте актуальную версию
    hooks:
      # Запускает линтер (проверка на ошибки и стиль)
      - id: ruff
        args: [--fix] # Автоматически исправлять то, что можно
      # Запускает форматтер (аналог Black)
      - id: ruff-format