version: '3.8'

services:
  db:
    image: postgres:15-alpine
    container_name: auth_system_db
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env
    ports:
      - "5432:5432"

  app:
    build: .
    container_name: auth_system_app
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    env_file:
      - ./.env
    depends_on:
      - db

volumes:
  postgres_data: