[tool.ruff]
# Длина строки, как у Black
line-length = 88

[tool.ruff.lint]
# Наборы правил для проверки:
# E, W: стандартные ошибки и предупреждения pycodestyle
# F: ошибки Pyflakes (неиспользуемые импорты, неопределенные переменные и т.д.)
# I: правила для сортировки импортов (isort)
select = ["E", "W", "F", "I"]

[tool.ruff.lint.isort]
# Папки
known-first-party = ["config", "apps"]
