[tool.ruff]
# Устанавливаем длину строки, как у Black
line-length = 88

[tool.ruff.lint]
# Выбираем наборы правил для проверки:
# E, W: стандартные ошибки и предупреждения pycodestyle
# F: ошибки Pyflakes (неиспользуемые импорты, неопределенные переменные и т.д.)
# I: правила для сортировки импортов (isort)
select = ["E", "W", "F", "I"]

[tool.ruff.lint.isort]
# Очень важная секция!
# Указываем Ruff, какие папки считать "своими", чтобы он правильно
# группировал импорты (сначала библиотеки, потом наши приложения).
known-first-party = ["config", "apps"]
